### ISSUE TITLE
最新编译失败

### ISSUE THREAD

**Issue by GodROS** [garypang13/OpenWrt#268]
大佬看下，dnsmasq compile
    make[3] -C package/network/services/dnsmasq compile
    ERROR: package/network/services/dnsmasq failed to build (build variant: full).

你库里的提示 ，因为oaf最新源码导致的，我注释掉了，出现了dnsmasq错误。
make[3] -C feeds/custom/oaf compile
    ERROR: package/feeds/custom/oaf failed to build.

**Comment by garypang13** [comment]
dnsmasq问题已经修复

oaf 这个要等oaf插件作者来修复. https://github.com/destan19/OpenAppFilter/issues/81

**Comment by GodROS** [comment]
嗯，大佬固件棒棒的。bypass+dnsfilter+gogproxy。还差个石像鬼qos。
