### ISSUE TITLE
R2S启用Bypass后ipv6无法正常使用

### ISSUE THREAD

**Issue by HalcyonAzure** [garypang13/OpenWrt#279]
这个能通过设置修改成启用ipv6吗..

**Comment by garypang13** [comment]
开启智能模式后,国外网站的IPV6会自动屏蔽掉的,因为智能模式是所有国外网站都走代理,代理节点基本都是不支持IPV6的,所以必须屏蔽IPV6,国外网站要开启IPV6的话可以用gfwlist模式,这样就只是gfwlist里的域名会屏蔽IPV6

**Comment by HalcyonAzure** [comment]
感谢回复。
