### ISSUE TITLE
R2s的镜像，能否改到2G以内

### ISSUE THREAD

**Issue by gxhunter1982** [garypang13/OpenWrt#287]
现在最后一个分区1.95G，再加上前面几个分区，正好超过2G一点点，175M左右。
如果用2G的卡刷，最后一个分区会溢出。

能否稍微调小下最后一个分区大小，让2G的卡正好完整刷入。

**Comment by garypang13** [comment]
好的,我以为2G的卡已经绝迹了,

**Comment by garypang13** [comment]
我看了下应该是你的TF卡实际容量不足2G,大部分卡都是实际容量不够标注容量的

**Comment by gxhunter1982** [comment]
最近整理的时候翻出好几张以前买的2G的卡，金士顿、PNY和闪迪的都有。查了下，好几张可能是MLC的，所以想好好利用起来。

容量不足是所有存储厂商的惯例，说是1000和1024换算问题，我们用户也没办法。
我手里三个牌子的2G的刷进入，都是差这么一点点170-175M左右。

**Comment by gxhunter1982** [comment]
大神速度的，0203版已解决。
