### ISSUE TITLE
最新版本环境变量有问题

### ISSUE THREAD

**Issue by gxhunter1982** [garypang13/OpenWrt#296]
![0209](https://user-images.githubusercontent.com/78349261/107458782-ba002880-6b8f-11eb-8884-572395128f9c.PNG)

实测，8日和9日版环境变量有问题。

6日的镜像是没问题的，比较了下，好像是/etc/profile内容变动造成的。
6日版是
`export PATH="/usr/sbin:/usr/bin:/sbin:/bin"`
8日和之后版本是
`export PATH="%PATH%"`
不知道是不是这个原因

刚才解压看了下10号的版本，还是一样的文件，应该也有这问题。

**Comment by yaotutu** [comment]
加1
![image](https://user-images.githubusercontent.com/21394924/107462840-f0da3c80-6b97-11eb-9453-669ea14907f5.png)

**Comment by garypang13** [comment]
感谢反馈, 先刷回02.07版,

**Comment by gxhunter1982** [comment]
02.07版也是新的profile，应该也有问题

**Comment by gxhunter1982** [comment]
大神给力，0210的第二个版本已修正
