### ISSUE TITLE
Frpc使用Range批量穿透缺少高级设置

### ISSUE THREAD

**Issue by HalcyonAzure** [garypang13/OpenWrt#303]
需求产生原因:
FTP服务器需要映射21，50000-51000等多个端口，使用网页端后台一个一个添加不现实，希望通过手动修改Frpc.conf来使用range批量映射但是网页端读入失败。
自己的操作:
手动修改/tmp/etc/frpc.conf文件然后在网页端内重新启用Frpc连接（用find指令没找到其他的有关配置文件:( ）发现文件被覆盖。
希望得到的结果:
能在网页端内直接选择Range并且批量设置端口，或者能增加高级设置可以手动修改达到多个端口穿透的效果。

**Comment by HalcyonAzure** [comment]
问题已经解决，使用https://github.com/kuoruan/luci-app-frpc内的ipk安装后的Frpc带有Range的设置

**Comment by garypang13** [comment]
@HalcyonAzure 那我把仓库的luci-app-frpc换成这个好了,
