### ISSUE TITLE
openclash不能用了

### ISSUE THREAD

**Issue by yhl452493373** [garypang13/OpenWrt#311]
openclash启动后任然无法访问外网。Dashboard 控制面板进去后空白页面，提示404，Yacd 控制面板可以进入，但是切换节点啥的没用，最终还是上不了外网。

openclash为最新版，之前是正常的。我2月8号编译了一次，openclash都正常，20号编译后就不行了。

**Comment by garypang13** [comment]
openclash和最新的openwrt不兼容, 暂时不要更新, 等openclash上游更新.

**Comment by xbingc** [comment]
> openclash和最新的openwrt不兼容, 暂时不要升级系统, 等openclash上游更新.

升级完才看到这个贴子……有办法回退固件版本吗？看OC的版本有阵子没动了，担心不知道要等多久

**Comment by yhl452493373** [comment]
> openclash和最新的openwrt不兼容, 暂时不要升级系统, 等openclash上游更新.

难受。。以后多装个科学上网算了。。

**Comment by garypang13** [comment]
https://github.com/vernesong/OpenClash/issues/1223 作者应该很快会修复的.

**Comment by garypang13** [comment]
已修复,去软件包中更新openclash即可.

**Comment by yhl452493373** [comment]
> 已修复,去软件包中更新openclash即可.

感谢
