### ISSUE TITLE
从plus+过来，bypass找不到不走代理的LAN设置方式

### ISSUE THREAD

**Issue by alexallen1** [garypang13/OpenWrt#320]
请教，让lan某ip不走代理方式
这里似乎找不到填写【不走代理的LAN IP】地方~
![image](https://user-images.githubusercontent.com/79105799/110154656-7495ea80-7e1f-11eb-8492-dc21b6678d1a.png)

**Comment by garypang13** [comment]
内网主机列表 中选择即可.

**Comment by alexallen1** [comment]
谢谢回复

**Comment by alexallen1** [comment]
@garypang13 另外，iphone wifi连接后，tg使用自带多个代理全部转圈圈无法收发信息（tg代理是正常的）。手机关掉wifi后tg秒连上。
设置是下图这样，不知道是我设置问题还是其他问题
![image](https://user-images.githubusercontent.com/79105799/110247922-8c00df00-7fa9-11eb-99e9-48bd2179c51d.png)
