### ISSUE TITLE
K2p目前的Bypass配置跑起来吃力, 希望用PDNSD取代SmartDNS

### ISSUE THREAD

**Issue by lon91ong** [garypang13/OpenWrt#343]
如题, 参考[LEDE项目下的讨论](https://github.com/coolsnowwolf/lede/issues/2551), 感觉smartdns确实没必要, 有点浪费资源
对于K2p标准板(16m闪存+128m内存)来说这点浪费就需要斤斤计较一番了
[dnscrypt-proxy2的方法似乎也不错](https://github.com/coolsnowwolf/lede/issues/2551#issuecomment-568382313)
希望采纳

**Comment by lon91ong** [comment]
这几天用下来, 时不时的国内网络无法访问, 需要重启一下才能正常

**Comment by NagaseKouichi** [comment]
doh可以用https-dns-proxy代替，TCP也可以用DNS-Forwarder代替

**Comment by garypang13** [comment]
DNS要满足两个要求
1. 支持 doh
2. 能单独屏蔽国外走代理网站的ipv6,而不影响国内网站的IPV6
smartdns 并不完美,有一些小问题, 但这是妥协后的唯一解决方案.
