### ISSUE TITLE
AC2100新版4.7固件5G和2.4G有严重的限速问题。

### ISSUE THREAD

**Issue by johanlike** [garypang13/OpenWrt#352]
自从更新了从3.27固件更新到了4.7。2.4G的网速从原来的100Mb下降到了只有可怜的15Mbps，5G网速从原来的330Mbps下降到了只有可怜的80Mbps，所有设置均尝试过均无效。

**Comment by johanlike** [comment]
4.12版本无改善。

**Comment by garypang13** [comment]
是不保留配置全新刷的吗, 我没有ac2100, 没法做测试.

**Comment by johanlike** [comment]
> 是不保留配置全新刷的吗，我没有ac2100，没法做测试。

是的，从刷底包还有双清刷的。而且拿来做中继AP也不好用了。不能在中继WIFI的情况下接着创建自己一个自定义的WIFI。中继WIFI是什么名字创建出来就是什么名字。目前看来3.27的版本最好用。新版160MHZ也没了

**Comment by johanlike** [comment]
更新太慢。已放弃该项目.
