### ISSUE TITLE
Bypass国内网站域名解析没有走smartdns

### ISSUE THREAD

**Issue by buggy-go** [garypang13/OpenWrt#355]
![image](https://user-images.githubusercontent.com/82141687/114290345-9b47e080-9ab1-11eb-9c50-d45c08cbc6f9.png)
![image](https://user-images.githubusercontent.com/82141687/114290356-aef34700-9ab1-11eb-89fb-cb84a5014fb2.png)

**Comment by garypang13** [comment]
默认关闭了smartdns的测速功能,会返回多个IP.
